name: CI

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build HBL binary
      run: |
        docker build . -t builder
        docker run --rm -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@v2
      with:
       name: HokakuCafe_hbl
       path: "*.rpx"
    - name: Build setup module
      run: |
        docker run --rm -v ${PWD}:/project builder make clean
        docker run --rm -v ${PWD}:/project builder make SETUP_MODULE=1
    - uses: actions/upload-artifact@v2
      with:
       name: HokakuCafe_setup_module
       path: "*.rpx"
